# -*- coding: utf-8 -*-
"""Envdata

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/122kdodm_Mx6QT6VlkH07_duU0kfL6Q0v

# Installation
"""

# run this cell to install pycaret in Google Colab
!pip install pycaret

# If you are using Jupyter notebook, you can pip install pycaret using jupyter notebook or command line
# pip install pycaret

from pycaret.utils import version
version()

"""# 1. Importing Dataset"""

import pandas as pd
data = pd.read_csv('Projec_final.csv')
data.info()
data

"""# 2. Setting up Environment"""

from pycaret.classification import setup

# Configurar o ambiente PyCaret
exp = setup(data, target='Enviroment', session_id=123)

data.head()

"""# 3. Compare Models"""

from pycaret.classification import compare_models
compare_models()

"""# 4. Create Model"""

from pycaret.classification import create_model
knn = create_model('knn')

"""# 5. Tune Model"""

from pycaret.classification import tune_model
tuned_knn = tune_model(knn)

print(tuned_knn)

print(tuned_knn)

"""# 6. Ensemble Model"""

from pycaret.classification import ensemble_model
bagged_knn = ensemble_model(knn)

# Change the method to 'Bagging'
bagged_knn = ensemble_model(knn, method = 'Bagging')

"""# 7. Blend Models"""

knn = create_model('knn', verbose=False)

!pip install pycaret

from pycaret.classification import *
blended_model = blend_models(estimator_list=[knn], method='soft')

blended_model.estimators

"""# 8. Analyze Model"""

plot_model(tuned_knn)

plot_model(tuned_knn, plot = 'confusion_matrix')

plot_model(blended_model, plot = 'threshold')

plot_model(blended_model, plot = 'pr')

plot_model(tuned_knn, plot = 'vc')

plot_model(tuned_knn, plot = 'boundary')

plot_model(bagged_knn, plot = 'boundary')

plot_model(blended_model, plot = 'boundary')

evaluate_model(tuned_knn)

"""# Learning Resources:

- PyCaret Classification Module : https://www.pycaret.org/classification
- Binary Classification Tutorial (Level Beginner) : https://pycaret.org/clf101/
- Binary Classification Tutorial (Level Intermediate) : https://pycaret.org/clf102/
- Kaggle Titanic Predictions (Video Tutorial) : https://www.youtube.com/watch?v=nqMM6rngNCA
"""